#!/usr/bin/env python3
"""Build STM32 encoder LUTs from original-method guarded round-trip sweeps."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import numpy as np


LUT_SIZE = 256
STOP_MARGIN_DEG = 3.0
UNOBSERVED_END_MARGIN_DEG = 1.0


def load_axis(
    path: Path, expected_axis: int | None = None
) -> tuple[dict[str, np.ndarray], float, bool]:
    rows: dict[str, list[tuple[float, float]]] = {"F": [], "R": []}
    far_stop = None
    nonzero_status = 0
    for line in path.read_text(errors="replace").splitlines():
        match = re.match(
            r"FAR STOP(?: axis (\d+))? confirmed early at ([0-9.]+) deg", line
        )
        if match and (
            match.group(1) is None or int(match.group(1)) == expected_axis
        ):
            far_stop = float(match.group(2))
        if not line.startswith("MAGDATA,"):
            continue
        fields = line.split(",")
        if len(fields) != 7:
            continue
        if expected_axis is not None and int(fields[1]) != expected_axis:
            continue
        direction = fields[2]
        command_deg = float(fields[3])
        raw_from_home = float(fields[4])
        status = int(fields[6])
        nonzero_status += status != 0
        rows[direction].append((raw_from_home, command_deg))

    if nonzero_status:
        raise ValueError(f"{path}: {nonzero_status} samples have encoder status flags")
    if min(len(rows["F"]), len(rows["R"])) < 100:
        raise ValueError(f"{path}: incomplete forward/reverse capture")

    arrays = {}
    for direction, values in rows.items():
        data = np.asarray(values, dtype=float)
        data = data[np.argsort(data[:, 0])]
        # A stop can produce repeated raw inputs.  Average their commanded values so
        # interpolation remains defined, although the stop region is excluded below.
        raw, inverse = np.unique(data[:, 0], return_inverse=True)
        command = np.zeros_like(raw)
        count = np.zeros_like(raw)
        np.add.at(command, inverse, data[:, 1])
        np.add.at(count, inverse, 1)
        arrays[direction] = np.column_stack((raw, command / count))

    command_max = max(value[1] for value in rows["F"])
    safe_command = (
        far_stop - STOP_MARGIN_DEG
        if far_stop is not None
        else command_max - UNOBSERVED_END_MARGIN_DEG
    )
    return arrays, safe_command, far_stop is not None


def build_lut(arrays: dict[str, np.ndarray], safe_command: float) -> tuple[int, np.ndarray]:
    raw_at_limit = []
    for data in arrays.values():
        order = np.argsort(data[:, 1])
        command_sorted = data[order, 1]
        raw_sorted = data[order, 0]
        raw_at_limit.append(float(np.interp(safe_command, command_sorted, raw_sorted)))
    raw_max = int(np.floor(min(raw_at_limit)))
    if raw_max <= 0:
        raise ValueError("calibration has no positive raw range")

    grid = np.linspace(0.0, float(raw_max), LUT_SIZE)
    estimates = []
    for data in arrays.values():
        estimates.append(np.interp(grid, data[:, 0], data[:, 1]))
    lut = np.mean(estimates, axis=0)
    lut -= lut[0]
    lut[0] = 0.0
    lut = np.maximum.accumulate(lut)
    return raw_max, lut


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("logs", nargs=3, type=Path, help="axis 0, 1, and 2 logs")
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--manifest", required=True, type=Path)
    args = parser.parse_args()

    axes = []
    for axis, path in enumerate(args.logs):
        arrays, safe_command, stop_observed = load_axis(path, axis)
        raw_max, lut = build_lut(arrays, safe_command)
        axes.append(
            {
                "axis": axis,
                "source": str(path),
                "raw_max": raw_max,
                "max_deg": float(lut[-1]),
                "stop_observed": stop_observed,
                "stop_margin_deg": STOP_MARGIN_DEG if stop_observed else None,
                "unobserved_end_margin_deg": None if stop_observed else UNOBSERVED_END_MARGIN_DEG,
                "lut": lut,
            }
        )

    lines = [
        "// Generated by software/EncoderMonitor/build_stm32_calibration.py.",
        "// Source: guarded STM32 adaptation of the original calibration; do not hand-edit.",
        "#pragma once",
        "#include <stdint.h>",
        "namespace Stm32Calibration {",
        f"constexpr uint16_t LUT_SIZE = {LUT_SIZE};",
        "constexpr bool HOME_REFERENCE_AFTER_BACKOFF = true;",
        "struct AxisLut { int32_t raw_max; float max_deg; float position_deg[LUT_SIZE]; };",
        "static const AxisLut AXIS[3] = {",
    ]
    for item in axes:
        values = item["lut"]
        lines.append(f"  {{ {item['raw_max']}, {item['max_deg']:.7f}f, {{")
        for start in range(0, LUT_SIZE, 8):
            chunk = ", ".join(f"{value:.7f}f" for value in values[start : start + 8])
            lines.append("    " + chunk + ("," if start + 8 < LUT_SIZE else ""))
        lines.append("  } },")
    lines += ["};", "}  // namespace Stm32Calibration", ""]
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text("\n".join(lines))

    manifest = {
        "format": 1,
        "lut_size": LUT_SIZE,
        "position_units": "degrees from the 1.8-degree post-home backoff reference",
        "home_reference_after_backoff": True,
        "generation": "midpoint of original-method guarded forward/reverse curves",
        "axes": [
            {key: value for key, value in item.items() if key != "lut"}
            for item in axes
        ],
    }
    args.manifest.parent.mkdir(parents=True, exist_ok=True)
    args.manifest.write_text(json.dumps(manifest, indent=2) + "\n")
    for item in axes:
        print(
            f"axis {item['axis']}: raw 0..{item['raw_max']}, "
            f"calibrated 0..{item['max_deg']:.3f} deg"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
